#!/usr/local/cpanel/3rdparty/bin/perl

use Cpanel::Version ();

if ( $Cpanel::Version::MAJORVERSION < 11.56 ) {
    #
    print "This addon requires 11.56 or later.\n";
    exit(1);
}

mkdir( "/usr/local/cpanel/whostmgr/docroot/cgi/addons",                 0755 );
mkdir( "/usr/local/cpanel/whostmgr/docroot/cgi/addons/MailAccountManager", 0700 );
system('cp -ia MailAccountManager/* /usr/local/cpanel/whostmgr/docroot/cgi/addons/MailAccountManager/ > /dev/null 2>&1');

mkdir( "/var/cpanel/apps",                        0755 );
mkdir( "/var/cpanel/addons",                      0755 );
mkdir( "/var/cpanel/addons/MailAccountManager",      0700 );
mkdir( '/var/cpanel/addons/MailAccountManager/perl', 0700 );


if ( -x '/usr/local/cpanel/bin/register_appconfig' ) {
    install( "-o", "root", "-g", "wheel", "-m" . "0700", "cgi/index.cgi", "/usr/local/cpanel/whostmgr/docroot/cgi/addons/MailAccountManager/index.cgi" );
    system '/usr/local/cpanel/bin/register_appconfig', "appconfig/MailAccountManager.conf";
}
else {
    install( "-o", "root", "-g", "wheel", "-m" . "0700", "cgi/webmailgen.cgi",  "/usr/local/cpanel/whostmgr/docroot/cgi/webmailgen.cgi" );
    install( "-o", "root", "-g", "wheel", "-m" . "0600", "appconfig/MailAccountManager.conf", "/var/cpanel/apps/MailAccountManager.conf" );
}

mkdir( "/usr/local/cpanel/whostmgr/docroot/addon_plugins", 0755 ) if !-e "/usr/local/cpanel/whostmgr/docroot/addon_plugins";
install( "-o", "root", "-g", "wheel", "-m" . "0600", "icon/ico-MailAccountManager.png", "/usr/local/cpanel/whostmgr/docroot/addon_plugins/ico-MailAccountManager.png" );

print "cPanel MailAccountManager installed into WHM.\n";

exit(0);

sub install {
    system( "/usr/bin/install", @_ );
}
